local colors = {
  -- content here will not be touched
  -- PATCH_OPEN
Normal = {fg = "#B1C3D2", bg = "#121C26"},
CmpItemMenu = {link = "Normal"},
NormalFloat = {link = "Normal"},
NormalNC = {link = "Normal"},
NormalSB = {link = "Normal"},
TabLineFill = {link = "Normal"},
TelescopeNormal = {link = "Normal"},
TelescopePreviewNormal = {link = "Normal"},
Bold = {bold = true},
["@text.strong"] = {link = "Bold"},
Boolean = {fg = "#EDABC5"},
["@boolean"] = {link = "Boolean"},
Border = {fg = "#38444C"},
FloatBorder = {link = "Border"},
TelescopeBorder = {link = "Border"},
VertSplit = {link = "Border"},
Character = {fg = "#E7A56F"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#848F9F"},
CmpItemAbbrDeprecated = {fg = "#7A8390", strikethrough = true},
CmpItemKind = {fg = "#8BB5DA"},
CmpItemKindColor = {fg = "#E78584"},
CmpItemKindCopilot = {fg = "#EDABAC"},
CmpItemKindEvent = {fg = "#8BB5DA"},
CmpItemKindInterface = {fg = "#F3D68C"},
CmpItemKindReference = {fg = "#E78584"},
CmpItemKindSnippet = {fg = "#BFADE6"},
CmpItemKindText = {fg = "#92D8D2"},
Comment = {fg = "#7A8390"},
["@comment"] = {link = "Comment"},
Conceal = {fg = "#405263"},
["@conceal"] = {link = "Conceal"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#D8B48D"},
["@constant"] = {link = "Constant"},
Cursor = {fg = "#90A4BB"},
CursorIM = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorLine = {bg = "#18283A"},
ColorColumn = {link = "CursorLine"},
CursorColumn = {link = "CursorLine"},
debugPC = {link = "CursorLine"},
CursorLineNr = {fg = "#848F9F"},
Debug = {fg = "#FB8D89", bg = "#2B2B3B"},
debugBreakpoint = {link = "Debug"},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
qfSeparator = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
LspDiagnosticsDefaultError = {link = "DiagnosticError"},
LspDiagnosticsFloatingError = {link = "DiagnosticFloatingError"},
LspDiagnosticsFloatingHint = {link = "DiagnosticFloatingHint"},
LspDiagnosticsFloatingInfo = {link = "DiagnosticFloatingInfo"},
LspDiagnosticsFloatingWarning = {link = "DiagnosticFloatingWarn"},
DiagnosticHint = {fg = "#848F9F"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
LspDiagnosticsDefaultHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#92D8D2"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
LspDiagnosticsDefaultInformation = {link = "DiagnosticInfo"},
LspDiagnosticsSignError = {link = "DiagnosticSignError"},
LspDiagnosticsSignHint = {link = "DiagnosticSignHint"},
LspDiagnosticsSignInformation = {link = "DiagnosticSignInfo"},
LspDiagnosticsSignWarning = {link = "DiagnosticSignWarn"},
DiagnosticUnderlineError = {sp = "#E78584", underdotted = true},
LspDiagnosticsUnderlineError = {link = "DiagnosticUnderlineError"},
DiagnosticUnderlineHint = {sp = "#848F9F", underdotted = true},
LspDiagnosticsUnderlineHint = {link = "DiagnosticUnderlineHint"},
DiagnosticUnderlineInfo = {sp = "#92D8D2", underdotted = true},
LspDiagnosticsUnderlineInformation = {link = "DiagnosticUnderlineInfo"},
DiagnosticUnderlineWarn = {sp = "#F3D68C", underdotted = true},
LspDiagnosticsUnderlineWarning = {link = "DiagnosticUnderlineWarn"},
DiagnosticVirtualTextError = {fg = "#FB8D89", bg = "#2B2B3B"},
LspDiagnosticsVirtualTextError = {link = "DiagnosticVirtualTextError"},
DiagnosticVirtualTextHint = {fg = "#848F9F", bg = "#141E2A"},
LspDiagnosticsVirtualTextHint = {link = "DiagnosticVirtualTextHint"},
DiagnosticVirtualTextInfo = {fg = "#A6E1E7", bg = "#1E3848"},
LspDiagnosticsVirtualTextInformation = {link = "DiagnosticVirtualTextInfo"},
DiagnosticVirtualTextWarn = {fg = "#FAC989", bg = "#202932"},
LspDiagnosticsVirtualTextWarning = {link = "DiagnosticVirtualTextWarn"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
LspDiagnosticsDefaultWarning = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#AFDB80", bg = "#1F3137"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#C7ABD3", bg = "#202741"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#FB8D89", bg = "#2B2B3B"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#90A4BB"},
diffLine = {link = "DiffText"},
Directory = {fg = "#8BB5DA"},
CmpItemKindFolder = {link = "Directory"},
qfFileName = {link = "Directory"},
Error = {fg = "#E78584"},
DiagnosticError = {link = "Error"},
ErrorMsg = {link = "Error"},
healthError = {link = "Error"},
qfError = {link = "Error"},
["@error"] = {link = "Error"},
["@text.danger"] = {link = "Error"},
["@exception"] = {link = "Exception"},
File = {fg = "#B1C3D2"},
CmpItemKindFile = {link = "File"},
Float = {fg = "#EDABC5"},
["@float"] = {link = "Float"},
FloatShadow = {bg = "#121C26"},
FloatShadowThrough = {bg = "#121C26"},
FoldColumn = {bg = "#121C26"},
Folded = {fg = "#7A8390", italic = true},
Function = {fg = "#8BB5DA"},
["@function"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@method"] = {link = "Function"},
["@method.call"] = {link = "Function"},
FuzzyMatch = {fg = "#D8B48D"},
CmpItemAbbrMatch = {link = "FuzzyMatch"},
CmpItemAbbrMatchFuzzy = {link = "FuzzyMatch"},
TelescopeMatching = {link = "FuzzyMatch"},
FzfLuaBorder = {fg = "#242833", bg = "#242833"},
FzfLuaColorsBg = {fg = "#121C26"},
FzfLuaColorsBgSel = {link = "FzfLuaColorsBg"},
FzfLuaColorsFg = {fg = "#B1C3D2"},
FzfLuaColorsFgSel = {link = "FzfLuaColorsFg"},
FzfLuaColorsHl = {fg = "#8BB5DA"},
FzfLuaColorsHlSel = {link = "FzfLuaColorsHl"},
FzfLuaColorsInfo = {fg = "#7A8390"},
FzfLuaColorsHeader = {link = "FzfLuaColorsInfo"},
FzfLuaColorsSpinner = {link = "FzfLuaColorsInfo"},
FzfLuaColorsMarker = {fg = "#87C092"},
FzfLuaColorsPointer = {fg = "#8BB5DA"},
FzfLuaColorsPrompt = {fg = "#BFADE6"},
FzfLuaNormal = {fg = "#B1C3D2", bg = "#242833"},
FzfLuaTitle = {fg = "#8BB5DA", bold = true},
GitSignsAdd = {fg = "#87C092"},
GitGutterAdd = {link = "GitSignsAdd"},
["@text.diff.add"] = {link = "GitSignsAdd"},
GitSignsChange = {fg = "#BFADE6"},
GitGutterChange = {link = "GitSignsChange"},
GitSignsDelete = {fg = "#E78584"},
GitGutterDelete = {link = "GitSignsDelete"},
["@text.diff.delete"] = {link = "GitSignsDelete"},
Identifier = {fg = "#B1C3D2"},
["@field"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
Include = {fg = "#92D8D2"},
Define = {link = "Include"},
Macro = {link = "Include"},
Italic = {italic = true},
["@text.emphasis"] = {link = "Italic"},
Keyword = {fg = "#BFADE6"},
Exception = {link = "Keyword"},
StorageClass = {link = "Keyword"},
["@include"] = {link = "Keyword"},
["@keyword"] = {link = "Keyword"},
LineNr = {fg = "#405263"},
qfLineNr = {link = "LineNr"},
LspCodeLens = {fg = "#7A8390", italic = true},
["@inlay.hint"] = {link = "LspCodeLens"},
LspParameter = {fg = "#EDABAC", italic = true},
LspReferenceText = {fg = "#9EBFEA", bg = "#1D3249"},
LspReferenceRead = {link = "LspReferenceText"},
LspReferenceWrite = {link = "LspReferenceText"},
LualineACommand = {fg = "#C7ABD3", bg = "#202741"},
LualineZCommand = {link = "LualineACommand"},
LualineAInactive = {fg = "#90A4BB", bg = "#1A2837"},
LualineZInactive = {link = "LualineAInactive"},
LualineAInsert = {fg = "#AFDB80", bg = "#1F3137"},
LualineZInsert = {link = "LualineAInsert"},
LualineANormal = {fg = "#9EBFEA", bg = "#1D3249"},
LualineZNormal = {link = "LualineANormal"},
LualineAReplace = {fg = "#FB8D89", bg = "#2B2B3B"},
LualineZReplace = {link = "LualineAReplace"},
LualineAVisual = {fg = "#A6E1E7", bg = "#1E3848"},
LualineZVisual = {link = "LualineAVisual"},
LualineYCommand = {link = "LualineBCommand"},
LualineYInactive = {link = "LualineBInactive"},
LualineYInsert = {link = "LualineBInsert"},
LualineBNormal = {fg = "#90A4BB", bg = "#141E2A"},
LualineBCommand = {link = "LualineBNormal"},
LualineBInactive = {link = "LualineBNormal"},
LualineBInsert = {link = "LualineBNormal"},
LualineBReplace = {link = "LualineBNormal"},
LualineBVisual = {link = "LualineBNormal"},
LualineYNormal = {link = "LualineBNormal"},
LualineYReplace = {link = "LualineBReplace"},
LualineYVisual = {link = "LualineBVisual"},
LualineXCommand = {link = "LualineCCommand"},
LualineXInactive = {link = "LualineCInactive"},
LualineXInsert = {link = "LualineCInsert"},
LualineCNormal = {fg = "#90A4BB", bg = "#1A2837"},
LualineCCommand = {link = "LualineCNormal"},
LualineCInactive = {link = "LualineCNormal"},
LualineCInsert = {link = "LualineCNormal"},
LualineCReplace = {link = "LualineCNormal"},
LualineCVisual = {link = "LualineCNormal"},
LualineXNormal = {link = "LualineCNormal"},
LualineXReplace = {link = "LualineCReplace"},
LualineXVisual = {link = "LualineCVisual"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#E8E6EA"},
ModeMsg = {fg = "#B1C3D2", bold = true},
MoreMsg = {fg = "#A6E1E7", bg = "#1E3848"},
MsgArea = {fg = "#B1C3D2"},
NonText = {fg = "#405263"},
EndOfBuffer = {link = "NonText"},
Whitespace = {link = "NonText"},
Number = {fg = "#8BB5DA"},
["@number"] = {link = "Number"},
CmpItemKindOperator = {link = "Operator"},
["@conditional.ternary"] = {link = "Operator"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#B1C3D2", bg = "#242833"},
PmenuSbar = {bg = "#242833"},
PmenuSel = {fg = "#9EBFEA", bg = "#1D3249"},
TabLineSel = {link = "PmenuSel"},
TelescopeSelection = {link = "PmenuSel"},
PmenuThumb = {fg = "#748390"},
PreProc = {fg = "#EDABAC"},
PreCondit = {link = "PreProc"},
["@attribute"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Punctuation = {fg = "#90A4BB"},
Delimiter = {link = "Punctuation"},
Operator = {link = "Punctuation"},
helpSectionDelim = {link = "Punctuation"},
markdownHeadingDelimiter = {link = "Punctuation"},
mkdCodeDelimiter = {link = "Punctuation"},
["@punctuation.delimiter"] = {link = "Punctuation"},
["@tag.delimiter"] = {link = "Punctuation"},
Question = {fg = "#7FD28F"},
QuickFixLine = {bg = "#141E2A", bold = true},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#FAC989", bg = "#202932", bold = true},
IncSearch = {link = "Search"},
SignColumn = {bg = "#121C26"},
SignColumnSB = {link = "SignColumn"},
Special = {fg = "#F08175"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
SpecialChar = {fg = "#EDABAC"},
["@character.special"] = {link = "SpecialChar"},
["@punctuation.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#EDABC5"},
SpecialKey = {fg = "#90A4BB"},
SpellBad = {sp = "#E78584", undercurl = true},
SpellCap = {sp = "#F3D68C", undercurl = true},
SpellLocal = {sp = "#92D8D2", undercurl = true},
SpellRare = {sp = "#848F9F", undercurl = true},
Statement = {fg = "#BFADE6"},
Conditional = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#B1C3D2", bg = "#141E2A"},
StatusLineNC = {fg = "#90A4BB", bg = "#141E2A"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#87C092"},
["@string"] = {link = "String"},
["@string.regex"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {fg = "#C7ABD3", bg = "#202741", bold = true},
Success = {fg = "#87C092"},
healthSuccess = {link = "Success"},
TabLine = {fg = "#848F9F", bg = "#121C26"},
["@tag"] = {link = "Tag"},
TelescopePromptBorder = {link = "TelescopeBorder"},
TelescopePromptNormal = {link = "TelescopeNormal"},
TelescopePromptCounter = {fg = "#7A8390"},
TelescopePromptPrefix = {fg = "#E78584"},
TelescopePromptTitle = {fg = "#BFADE6", bold = true},
TelescopeSelectionCaret = {fg = "#E78584"},
TelescopeTitle = {fg = "#8BB5DA", bold = true},
TelescopeResultsTitle = {link = "TelescopeTitle"},
TerminalColor0 = {fg = "#121C26"},
TerminalColor1 = {fg = "#E78584"},
TerminalColor10 = {fg = "#9BC0A5"},
TerminalColor11 = {fg = "#E5DCAE"},
TerminalColor12 = {fg = "#97B5D8"},
TerminalColor13 = {fg = "#AC93E1"},
TerminalColor14 = {fg = "#71D1C7"},
TerminalColor15 = {fg = "#90A4BB"},
TerminalColor2 = {fg = "#87C092"},
TerminalColor3 = {fg = "#F3D68C"},
TerminalColor4 = {fg = "#8BB5DA"},
TerminalColor5 = {fg = "#BFADE6"},
TerminalColor6 = {fg = "#92D8D2"},
TerminalColor7 = {fg = "#B1C3D2"},
TerminalColor8 = {fg = "#7A8390"},
TerminalColor9 = {fg = "#F08175"},
Title = {fg = "#E8E6EA", bold = true},
helpHeader = {link = "Title"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#9EBFEA", bg = "#1D3249", italic = true},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#9BC0A5"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@definition.type"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.builtin"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
URI = {fg = "#92D8D2", underline = true},
helpHyperTextJump = {link = "URI"},
markdownLinkText = {link = "URI"},
markdownUrl = {link = "URI"},
mkdLink = {link = "URI"},
["@text.uri"] = {link = "URI"},
Underlined = {underline = true},
Winseparator = {link = "VertSplit"},
Visual = {bg = "#22446D"},
VisualNOS = {link = "Visual"},
Warning = {fg = "#F3D68C"},
DiagnosticWarn = {link = "Warning"},
WarningMsg = {link = "Warning"},
healthWarning = {link = "Warning"},
["@text.warning"] = {link = "Warning"},
WildMenu = {bg = "#242833"},
diffFile = {fg = "#BFADE6"},
diffIndexLine = {fg = "#BFADE6"},
diffNewFile = {fg = "#8BB5DA"},
diffOldFile = {fg = "#90A4BB"},
helpCommand = {fg = "#B1C3D2", bg = "#141E2A"},
helpExample = {fg = "#90A4BB"},
markdownH1 = {fg = "#E8E6EA", bold = true},
markdownH2 = {link = "markdownH1"},
markdownH3 = {link = "markdownH1"},
mkdCodeStart = {fg = "#B1C3D2", bg = "#121C26", bold = true},
mkdCodeEnd = {link = "mkdCodeStart"},
["@definition.constant"] = {link = "@constant"},
["@constructor"] = {},
CmpItemKindConstructor = {link = "@constructor"},
["@definition"] = {},
CmpItemKindConstant = {link = "@definition.constant"},
CmpItemKindEnum = {link = "@definition.enum"},
CmpItemKindField = {link = "@definition.field"},
CmpItemKindFunction = {link = "@definition.function"},
CmpItemKindMethod = {link = "@definition.method"},
CmpItemKindModule = {link = "@definition.namespace"},
CmpItemKindUnit = {link = "@definition.namespace"},
CmpItemKindClass = {link = "@definition.type"},
CmpItemKindStruct = {link = "@definition.type"},
["@definition.var"] = {},
CmpItemKindVariable = {link = "@definition.var"},
["@definition.associated"] = {link = "@definition"},
["@definition.enum"] = {link = "@definition"},
["@definition.field"] = {link = "@definition"},
["@definition.import"] = {link = "@definition"},
CmpItemKindEnumMember = {link = "@field"},
CmpItemKindValue = {link = "@field"},
["@function.builtin"] = {fg = "#8BB5DA"},
["@definition.macro"] = {link = "@function.macro"},
["@definition.function"] = {link = "@function"},
["@keyword.return"] = {fg = "#F08175"},
CmpItemKindKeyword = {link = "@keyword"},
["@keyword.function"] = {link = "@keyword"},
["@keyword.operator"] = {link = "@keyword"},
["@label"] = {},
["@lsp.mod.declaration.c"] = {},
["@lsp.mod.definition.c"] = {},
["@lsp.mod.globalScope.c"] = {},
["@definition.method"] = {link = "@method"},
["@namespace"] = {fg = "#F08175"},
["@definition.namespace"] = {link = "@namespace"},
["@none"] = {},
CmpItemKindTypeParameter = {link = "@parameter"},
["@definition.parameter"] = {link = "@parameter"},
CmpItemKindProperty = {link = "@property"},
["@punctuation.bracket"] = {link = "@punctuation.delimiter"},
["@reference"] = {},
["@scope"] = {},
["@symbol"] = {},
["@text"] = {},
["@text.environment"] = {},
["@text.environment.name"] = {},
["@text.literal"] = {},
["@text.math"] = {link = "@text.literal"},
["@text.note"] = {underline = true},
["@text.quote"] = {fg = "#90A4BB", italic = true},
["@text.strike"] = {strikethrough = true},
["@text.underline"] = {underline = true},
["@type.qualifier"] = {fg = "#F08175"},
["@variable"] = {},
["@variable.builtin"] = {fg = "#BFADE6"},
  -- PATCH_CLOSE
  -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd 'highlight clear'
vim.cmd 'set t_Co=256'
vim.cmd "let g:colors_name='chroma-static'"

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
